%% Session-scoped queries (project_license/1 and dependency/2 asserted at runtime).

%% dependency(Name, LicenseAtom) — generated by Python session facts.

project_obligation(Obligation) :-
    project_license(Project),
    obligation(Project, Obligation).

dependency_obligation(DepName, Obligation) :-
    dependency(DepName, DepLicense),
    obligation(DepLicense, Obligation).

dependency_conflict(DepName, Reason) :-
    project_license(Project),
    dependency(DepName, DepLicense),
    incompatible(Project, DepLicense, Reason).

dependency_compatible(DepName) :-
    project_license(Project),
    dependency(DepName, DepLicense),
    compatible(Project, DepLicense).

dependency_risk(DepName, Risk) :-
    project_license(Project),
    dependency(DepName, DepLicense),
    risk_level(Project, DepLicense, Risk).

project_requires_source_disclosure :-
    project_license(L),
    requires_source_disclosure(L).

project_requires_network_disclosure :-
    project_license(L),
    requires_network_source_disclosure(L).

project_requires_attribution :-
    project_license(L),
    requires_attribution(L).
